# Generated by Django 5.1.2 on 2024-10-23 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionitem',
            name='created_at',
        ),
    ]
