# Generated by Django 5.1.2 on 2024-10-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='current_price',
            field=models.IntegerField(),
        ),
    ]
