# Generated by Django 5.1.2 on 2024-10-31 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_auctionitem_current_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='auction_duration',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='phone_number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='current_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='AuctionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='auction_images/')),
                ('auction_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.auctionitem')),
            ],
        ),
    ]
