# Generated by Django 5.1.5 on 2025-02-04 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='sender',
        ),
    ]
