# Generated by Django 5.1.2 on 2024-11-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
