# Generated by Django 5.1.3 on 2024-11-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='category',
            field=models.CharField(choices=[('electronics', 'Elektronika'), ('appliances', 'Kućni aparati'), ('jewelry', 'Nakit i Satovi'), ('clothing', 'Odeća i Obuća'), ('toys', 'Igračke i Video igre'), ('furniture', 'Nameštaj'), ('sports', 'Sport i Oprema'), ('collectibles', 'Kolekcionarstvo i Antikviteti'), ('media', 'Knjige, Filmovi i Muzika'), ('tools', 'Alati i Oprema za rad'), ('vehicles', 'Automobili i Motocikli'), ('real-estate', 'Nekretnine'), ('food', 'Hrana i Piće'), ('other', 'Ostalo')], default='other', max_length=50),
        ),
    ]
