# Generated by Django 5.1.3 on 2024-11-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auctionitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='category',
            field=models.CharField(default='other', max_length=50),
        ),
    ]
