# Generated by Django 5.1.3 on 2024-11-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_customuser_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='last_notified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
