# Generated by Django 5.1.3 on 2024-11-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auctionitem_last_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='last_bid_notified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
