# Generated by Django 5.1.3 on 2024-11-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auctionitem_last_bid_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
