# Generated by Django 5.1.3 on 2024-11-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auctionitem_is_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
