version: '3'

services:
  redis:
    image: redis:latest
    restart: always  # Osigurava da Redis ponovo pokrene ako padne
    ports:
      - "6379:6379"


  web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis  # Uverite se da web servis zavisi od Redis servisa
    environment:
      - CELERY_BROKER_URL=redis://red-cv8ri9vnoe9s73atfs0g:6379  # Ovo postavlja Redis kao broker za Celery
      - CELERY_RESULT_BACKEND=redis://red-cv8ri9vnoe9s73atfs0g:6379
      - PYTHONPATH=/code/VelikaAukcija
      - DJANGO_SETTINGS_MODULE=backend.settings

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  celery:
    build: .
    command: celery -A backend worker --loglevel=info
    environment:
    - CELERY_BROKER_URL=redis://red-cv8ri9vnoe9s73atfs0g:6379  # Ovo postavlja Redis kao broker za Celery
    - CELERY_RESULT_BACKEND=redis://red-cv8ri9vnoe9s73atfs0g:6379
    depends_on:
      - redis
      - db

  celery-beat:
    build: .
    environment:
    - CELERY_BROKER_URL=redis://red-cv8ri9vnoe9s73atfs0g:6379/0  # Ovo postavlja Redis kao broker za Celery
    - CELERY_RESULT_BACKEND=redis://red-cv8ri9vnoe9s73atfs0g:6379
    command: celery -A backend beat --loglevel=info
    depends_on:
      - redis
      - db
