version: '3'

services:
  web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - CELERY_BROKER_URL=redis://red-cv8ri9vnoe9s73atfs0g:6379/0
      - CELERY_RESULT_BACKEND=redis://red-cv8ri9vnoe9s73atfs0g:6379/0
      - PYTHONPATH=/code/VelikaAukcija
      - DJANGO_SETTINGS_MODULE=backend.settings

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  celery:
    build: .
    command: celery -A backend worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://red-cv8ri9vnoe9s73atfs0g:6379/0
      - CELERY_RESULT_BACKEND=redis://red-cv8ri9vnoe9s73atfs0g:6379/0
    depends_on:
      - db

  celery-beat:
    build: .
    command: celery -A backend beat --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://red-cv8ri9vnoe9s73atfs0g:6379/0
      - CELERY_RESULT_BACKEND=redis://red-cv8ri9vnoe9s73atfs0g:6379/0
    depends_on:
      - db
