version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  redis:
    image: redis:latest
    ports:
      - "6379:6379"  # Ovo omogućava pristup Redis-u na portu 6379 u Docker-u

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis  # Uverite se da web servis zavisi od Redis servisa
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0  # Ovo postavlja Redis kao broker za Celery

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  celery:
    build: .
    command: celery -A backend worker --loglevel=info
    depends_on:
      - redis
      - db

  celery-beat:
    build: .
    command: celery -A backend beat --loglevel=info
    depends_on:
      - redis
      - db
